### Test Primes API
GET http://localhost:3000/numbers/p

### Test Fibonacci API
GET http://localhost:3000/numbers/f

### Test Even Numbers API
GET http://localhost:3000/numbers/e

### Test Random Numbers API
GET http://localhost:3000/numbers/r

### Test Invalid ID
GET http://localhost:3000/numbers/x
